DROP TABLE IF EXISTS bookings;
CREATE TABLE bookings(
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
users_id	INTEGER REFERENCES users
(id) ON
DELETE CASCADE,
venue_id INTEGER REFERENCES venues
(id) ON
DELETE CASCADE NOT NULL,
booking_date date
);
INSERT INTO bookings(users_id, venue_id, booking_date)
VALUES(null,1,'2020-10-29'),(null,2,'2020-10-29'),(null,4,'2020-10-29'),(null,3,'2020-10-30'),
(null,1,'2020-11-01'),(null,4,'2020-10-28'),
(null,5,'2020-10-25'),(null,5,'2020-10-27'),(null,3,'2020-10-27'),(null,3,'2020-10-25'),(null,3,'2020-10-25'),(null,3,'2020-10-25')